SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS


PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300  # degrees per second
PLAYER_SPEED = 200



'''PLAYER_ACCELERATION = 200
PLAYER_DRAG = 0.9
PLAYER_MAX_SPEED = 300
PLAYER_SHOOT_DELAY = 0.2  # seconds
PLAYER_LIVES = 3    # number of lives the player has
PLAYER_INVINCIBLE_TIME = 3  # seconds
PLAYER_INVINCIBLE_FLASH_RATE = 0.1  # seconds 
'''